[package]
name = "manga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
curl = "0.4.46"
ratatui = "0.26.1"
scraper = "0.19.0"
